module.exports = {
    OWNER_ID: process.env.OWNER_ID,
    GMAIL_ACCOUNT: process.env.GMAIL_ACCOUNT,
    GMAIL_CLIENT_ID: process.env.GMAIL_CLIENT_ID,
    GMAIL_CLIENT_SECRET: process.env.GMAIL_CLIENT_SECRET,
    GMAIL_ACCESS_TOKEN: process.env.GMAIL_ACCESS_TOKEN,
    GMAIL_REFRESH_TOKEN: process.env.GMAIL_REFRESH_TOKEN,
    REDIRECT_URI: process.env.REDIRECT_URI,
    REDIRECT_URI_2: process.env.REDIRECT_URI_2,
};